### ISSUE TITLE
Maybe change this function name?

### ISSUE THREAD

**Issue by RDIL** [cakebotpro/wordcloud#3]
https://github.com/cakebotpro/wordcloud/blob/4cb2dd90778f412b32a3e3aebce7523ff4dabcad/DiscordWC/__init__.py#L9
@paramt I’m thinking we override __str__() with this method.

**Comment by RDIL** [comment]
(Underscore underscore str underscore underscore because I’m on mobile)

**Comment by paramt** [comment]
Something like this? 

https://github.com/cakebotpro/wordcloud/blob/166f593bd9482449243be24370694157b72b1162/DiscordWC/__init__.py#L10

https://github.com/cakebotpro/wordcloud/blob/166f593bd9482449243be24370694157b72b1162/DiscordWC/__init__.py#L17

I can't find much info online, but from what I found, overriding the `__str__` function is used to change the string representation of the class, rather than what you're proposing

**Comment by paramt** [comment]
[Here's what I found](https://www.journaldev.com/22460/python-str-repr-functions)

Basically it changes the output of 

```python
wordcloud = DiscordWC(100, "#eee")
print(wordcloud)
```

from 

```
<__main__.DiscordWC object at 0x10ff22470>
```

to a custom string

**Comment by RDIL** [comment]
That’s what I mean, we make get words (which is a string) into the to string method
